controller_manager:
  ros__parameters:
    update_rate: 250 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    chessaton_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    chessaton_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

chessaton_arm_controller:
  ros__parameters:
    joints:
      - chessaton_joint1
      - chessaton_joint2
      - chessaton_joint3
      - chessaton_joint4
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      chessaton_joint1:
        p: 4000.0
        d: 10.0
        i: 250.0
        i_clamp: 15.0
      chessaton_joint2:
        p: 10000.0
        d: 25.0
        i: 600.0
        i_clamp: 45.0
      chessaton_joint3:
        p: 8000.0
        d: 20.0
        i: 450.0
        i_clamp: 30.0
      chessaton_joint4:
        p: 6000.0
        d: 15.0
        i: 300.0
        i_clamp: 30.0

chessaton_hand_controller:
  ros__parameters:
    joints:
      - left_finger_joint
      - right_finger_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      left_finger_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      right_finger_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
