controller_manager:
  ros__parameters:
    update_rate: 250 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    chessaton_arm_controller:
      # type: joint_trajectory_controller/JointTrajectoryController
      type: effort_controllers/JointGroupEffortController

    chessaton_hand_controller:
      # type: joint_trajectory_controller/JointTrajectoryController
      type: effort_controllers/JointGroupEffortController

chessaton_arm_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - chessaton_joint1
      - chessaton_joint2
      - chessaton_joint3
      - chessaton_joint4
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      chessaton_joint1:
        p: 4000.0
        d: 50.0
        i: 25.0
        i_clamp: 100.0
      chessaton_joint2:
        p: 10000.0
        d: 45.0
        i: 6.0
        i_clamp: 100.0
      chessaton_joint3:
        p: 8000.0
        d: 40.0
        i: 4.0
        i_clamp: 100.0
      chessaton_joint4:
        p: 6000.0
        d: 25.0
        i: 3.0
        i_clamp: 100.0

chessaton_hand_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_finger_joint
      - right_finger_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      left_finger_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 1.0
      right_finger_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 1.0
