# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - chessaton_arm_controller
  - chessaton_finger_left_controller
  - chessaton_finger_right_controller

chessaton_arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - chessaton_joint1
    - chessaton_joint2
    - chessaton_joint3
    - chessaton_joint4
    - virtual_roll_joint
    - virtual_yaw_joint

chessaton_finger_left_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - left_finger_joint

chessaton_finger_right_controller:
  action_ns: gripper_cmd
  type: GripperCommand
  default: true
  joints:
    - right_finger_joint