# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - chessaton_arm_controller
    - chessaton_hand_controller

  chessaton_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - chessaton_joint1
      - chessaton_joint2
      - chessaton_joint3
      - chessaton_joint4
  chessaton_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_finger_joint
      - right_finger_joint